yeongrok/0001-two-sum/0001-two-sum.js, yeongrok/0001-two-sum/README.md
Commit Hash | Description | Time Complexity
-------------|-------------|-------------------
8cdf6eca3b95be4db7964a67439dc7ff7d7ac32e | for문 중첩해서 모든 조합 경우의 수 확인 | O(n^2)
13bbdd97600b59d45d3b1e559d1c1194dcb3fbc2 | 배열을 오름차순 정렬한 다음 포인터 이용해서 확인 | O(nlogn)
3c6b1007f6a897b86d0237f2d1333357b99da5a7 | 찾으려는 값과, 그 쌍이 될 수 있는 index를 Map에 저장하면서 배열 순회 | O(n)
=> 1. Two Sum / Easy / JavaScript

eunjoo/0001-two-sum/0001-two-sum.ts, eunjoo/0002-add-two-numbers/README.md
+ Map을 사용해 nums 배열 순회
+ O(n)의 time complexity
=> 1. Two Sum / Easy / TypeScript

eunjoo/0001-two-sum/0001-two-sum.ts, eunjoo/0002-add-two-numbers/0002-add-two-numbers.ts, eunjoo/0002-add-two-numbers/README.md
+ **O(max(m,n))**
+ m은 l1의 길이, n은 l2의 길이
=> 2. Add Two Numbers / Medium / Typescript

yeongrok/0003-longest-substring-without-repeating-characters/0003-longest-substring-without-repeating-characters.js, yeongrok/0003-longest-substring-without-repeating-characters/README.md
Sliding Window 기법 사용 + 글자가 가장 마지막으로 등장한 위치를 기록하는 용도로 Map 사용
(Object보다 Map이 더 효율적)
Time Complexity, Space Complexity: O(n)
=> 3. Longest Substring Without Repeating Characters / Medium / JavaScript

eunjoo/0003-longest-substring-without-repeating-characters/0003-longest-substring-without-repeating-characters.ts, eunjoo/0003-longest-substring-without-repeating-characters/README.md
+ Set을 사용, startIndex & endIndex 모두 0으로 시작
+ endIndex를 1씩 더하면서 Set에 해당 문자를 저장하는데, 이때 중복되는 문자가 등장하면 startIndex를 1씩 더함
+ 문자열을 하나씩 훑기 때문에 시간 복잡도, 공간 복잡도 모두 O(n)
+ O(n)
=> 3. Longest Substring Without Repeating Characters / Medium / TypeScript

eunjoo/0004-median-of-two-sorted-arrays/0004-median-of-two-sorted-arrays.ts, eunjoo/0004-median-of-two-sorted-arrays/README.md
+ nums1과 nums2 배열을 순차적으로 돌면서, 크기순으로 sorting
+ 배열의 크기 역시 O(n+m)
=> 4. Median of Two Sorted Arrays / Hard / TypeScript

yeongrok/0004-median-of-two-sorted-arrays/0004-median-of-two-sorted-arrays.js, yeongrok/0004-median-of-two-sorted-arrays/README.md
- 시간 복잡도 O(m+n) :: 정확히는 O((m+n)/2 + 1)
- 공간 복잡도 O(m+n) :: 정확히는 O((m+n)/2 + 1)
- 두 배열을 합친 길이의 절반+1에 해당하는 만큼만 새로운 배열을 만듦
주어진 배열이 정렬되어 있으니 각각 마지막 요소를 비교해 pop해서 새 배열에 넣음
=> 중간값을 구할 수 있는 길이만큼만 새 배열을 만들고, 중간값 계산.
---
> The overall run time complexity should be `O(log (m+n))`.
라고 되어 있었는데 그만큼은 달성하지 못해서 갱장히 분함 지금.. 
은주의 정답 몹시 궁금
=> 4. Median of Two Sorted Arrays / Hard / JavaScript

eunjoo/0005-longest-palindromic-substring/0005-longest-palindromic-substring.ts, eunjoo/0005-longest-palindromic-substring/README.md
+ 문자열 탐색 시 0번째 문자부터 마지막 문자까지 순회
+ 해당 문자가 palindrome의 중간에 오는 문자가 됨.
+ 해당 문자를 기준으로 왼쪽 오른쪽으로 -1, +1씩을 하면서 palindrome이 되는 문자열을 탐색
+ 그 중 가장 긴 문자를 찾는다.
+ for 문 안에 while 문으로 탐색
=> 5. Longest Palindromic Substring / Medium / TypeScript

yeongrok/0005-longest-palindromic-substring/0005-longest-palindromic-substring.js, yeongrok/0005-longest-palindromic-substring/README.md
#10 싱크 오류로 닫혀버린 바람에 다시 씁니다요...
=> 5. Longest Palindromic Substring / Medium / JavaScript

eunjoo/0006-zigzag-conversion/0006-zigzag-conversion.ts, eunjoo/0006-zigzag-conversion/README.md
"PAYPALISHIRING"
`P   A   H   N`
`A P L S I I G`
`Y   I   R`
정답 - "PAHNAPLSIIGYIR"
규칙을 찾아서 수학적으로 계산한다. 
첫번째 열부터 세번째 열까지 순회하고, 각 글자를 훑기 때문
1. 공통 gap 이 있는 글자들 
+ gap은 numRows -2
**`P    A   H    N`**
**`A`**` P `**`L`**`S`**`I`**`I`**`G`**
**`Y    I   R`**
2. 맨첫줄과 맨 마지막줄을 제외한 가운데 열들의 불규칙적인 단어들 
+ gap은 2*(numRows - row - 1), row는 본인 열의 번호 
+ ex) "PAYPALISHIRING"에서 A와 P 사이 글자들의 수, P와 L 사이의 글자들의 수 를 수학적으로 계산 한 것
`P    A   H    N`
`A`**` P `**`L`**`S`**`I`**`I`**`G`
`Y    I   R`
=> 6. Zigzag Conversion / Medium / Typescript

yeongrok/0007-reverse-integer/0007-reverse-integer.js, yeongrok/0007-reverse-integer/README.md
=> 7. Reverse Integer / Medium / JavaScript

eunjoo/0007-reverse-integer/0007-reverse-integer.ts, eunjoo/0007-reverse-integer/README.md
7번을 먼저 풀었는데요,,, ㅎㅎ 워크샵에 오게되었는데 9번을 미리 못 풀었습니다.
시간이 남으면 꼭 9번도 풀어서 올리겠습니다 ^__^
**Time Complexity: O(n)
Space Complexity: O(n)**
Math.abs로 양수로 만들고, string으로 만든 뒤 reverse한다.
정해진 범위에 맞지 않는 경우 0으로 return 해주는 조건도 적용한다.
=> 7. Reverse Integer / Medium / TypeScript

0010-regular-expression-matching/README.md, yeongrok/0010-regular-expression-matching/0010-regular-expression-matching.js
- Time Complexity: O(2^p + s)
라고 하는데 어떻게 계산되는 건지 몰라서 찾아봤음
- https://stackoverflow.com/a/21702
- [Regular Expression Matching Can Be Simple And Fast](https://swtch.com/~rsc/regexp/regexp1.html)
=> 10. Regular Expression Matching / Hard / JavaScript

yeongrok/0011-container-with-most-water/0011-container-with-most-water.js, yeongrok/0011-container-with-most-water/README.md
- Time Complexity: O(n)
- Space Complexity: O(1)
- 일단 양쪽 끝을 기둥으로 삼아 물의 양 계산한 다음,
범위를 좁혀오면서 최대 물의 양 갱신해가는 방법
=> 11. Container With Most Water / Medium / JavaScript

eunjoo/0011-container-with-most-water/0011-container-with-most-water.ts, eunjoo/0011-container-with-most-water/README.md
left와 right를 양쪽 끝 x축 값으로 설정해 둔다.
left와 right 중 y축 값이 작은 x축 좌표를 가운데를 향해 가도록 움직인다.
Math.max를 사용해서 가장 큰 값을 return 하도록 한다.
=> 11. Container With Most Water / Medium / TypeScript

eunjoo/0010-regular-expression-matching/0010-regular-expression-matching.ts, eunjoo/0010-regular-expression-matching/README.md
+ 모르겠어서 찾아봄
+ https://learnersbucket.com/examples/algorithms/javascript-string-contains-substring/
+ **p.includes(str) => `O(N)`**
+ **s.match(p) => `O(1)`**
=> 10. Regular Expression Matching / Hard / Typescript

yeongrok/0013-roman-to-integer/0013-roman-to-integer.js, yeongrok/0013-roman-to-integer/README.md
주어진 로마 숫자의 끝에서부터(작은 수부터) 읽으면서 `sum`에 더해가는 방식
단, 앞 차례에 읽은 수보다 작은 수가 나오면 `sum`에서 더하지 않고 뺌 (`"IV"`라면 `5 - 1`로 계산하는 식)
- Time Complexity: O(n)
- Space Complexity: O(1)
=> 13. Roman to Integer / Easy / JavaScript

eunjoo/0015-3sum/0015-3sum.ts, eunjoo/0015-3sum/README.md
+ 배열을 오름차순으로 정렬
+ 첫번째 array에서 O(N)으로 순회
+ 두번째 while loop에서 L과 R 포인터를 사용해서 array 내부에서 순회하므로 O(N*N) => O(N^2)
+ 두번째 while loop에서 sum이 0보다 작은 경우는 L의 값을 배열의 오른쪽으로 이동하고, sum이 0보다 큰 경우는 R의 값을 왼쪽으로 이동한다.  sum이 0인 경우 정답 set에 담아주고, 중복을 피하기 위해서 같은 값인 경우 L++ R-- 를 해준다.
=> 15. 3Sum / Medium / TypeScript

yeongrok/0017-letter-combinations-of-a-phone-number/0017-letter-combinations-of-a-phone-number.js, yeongrok/0017-letter-combinations-of-a-phone-number/README.md
1. 번호와 글자 간 매핑을 Map으로 만든다
2. 숫자별 글자 배열 간 모든 조합의 경우를 `output`이라는 배열에 넣는다.
이를 위해, 각 배열을 순회할 포인터의 위치를 저장하는 `pointers` 배열을 만든다.
`pointers`의 가장 마지막 요소부터 +1 씩 해가며, Map에서 해당 글자를 찾아 조합을 만든다.
만약 `pointers[i]`가 가질 수 있는 최대값이 넘어가면, 다시 0으로 만들고 `pointers[i-1]`의 값을 +1 한다.
`pointers`의 모든 요소가 0이 되어버리는 시점에 조합 만들기를 멈추고 `output`을 반환한다.
n: digits의 길이
digit 별로 입력 가능한 글자의 개수가 3개 혹은 4개이므로,
가능한 조합의 수는 3^n ~ 4^n
조합의 수만큼 output에 저장해야 하므로 시간 복잡도와 공간 복잡도가 같음
=> 17. Letter Combinations of a Phone Number / Medium / JavaScript

eunjoo/0019-remove-nth-node-from-end-of-list/0019-remove-nth-node-from-end-of-list.ts, eunjoo/0019-remove-nth-node-from-end-of-list/README.md
+ head ListNode의 길이만큼 순회하기 때문에 time complexity는 O(N)
+ head ListNode의 길이만큼 데이터를 저장하고 있기 때문에 space complexity O(N)
head ListNode를 array에 하나씩 담아주고, 끝에서 n-1 번째의 다음 Node를 n+1번째 노드로 연결해준다.
이 때 n-1 번째 array item이 없는 경우는 n번째 요소가 head의 첫번째 요소라는 의미이기 때문에, 바로 head.next를 return 해준다.
=> 19. Remove Nth Node From End of List / Medium / TypeScript

yeongrok/0020-valid-parentheses/0020-valid-parentheses.js, yeongrok/0020-valid-parentheses/README.md
- 여는 괄호를 키로, 닫는 괄호를 값으로 하는 Map을 생성한다.
- 문자열 `s`를 순회하면서 여는 괄호가 나오면 stack에 쌓고, 닫는 괄호가 나오면 stack에서 요소를 꺼내 적절한 쌍인지 확인한다.
- 적절하지 않은 쌍이 나오거나, 문자열 `s`의 순회가 끝났는데 stack에 남아있는 요소가 있다면 `false`를 반환한다.
그렇지 않으면 `true`를 반환한다.
- n은 문자열의 길이. 문자열을 처음부터 끝까지 순회하며 비교 연산을 수행하므로
- 최악의 경우 최대 문자열의 길이만큼 stack size가 길어질 수 있음: O(n)
(가령 `s`가 `{{{{{`로 주어진 경우)
- 조건에 맞게 (`true`가 반환될 수 있게) 문자열이 주어진 경우 공간 복잡도는 최대 O(n/2)임
열린 괄호는 문자열 길이의 절반이고, 열린 괄호만 stack에 들어가기 때문
=> 20. Valid Parentheses / Easy / JavaScript

eunjoo/0020-valid-parentheses/0020-valid-parentheses.ts, eunjoo/0020-valid-parentheses/README.md
+ braket pair를 위한 map을 만들고 문자열을 순회하면서 여는 braket이 등장하면 닫은 braket을 stack에 넣어준다. 만약 닫는 braket이 등장하면 stack의 top에 쌓인 닫는 braket과 일치하는지 확인하고 stack에서 pop한다. 일치하지 않는 경우 false를 return해 준다. 더불어 문자열 순회가 끝난 후 stack에 pop하지 못한 braket이 남아있는 경우도 false를 return해 주도록 한다. 
+ 최대 s 문자열 길이 만큼 순회하기 때문에 최대 O(N)의 시간 복잡도 
+ 최대 s 문자열 길이 만큼 stack에 저장하기 때문에 최대 O(N)의 공간 복잡도
=> 20. Valid Parentheses / Easy / Typescript

eunjoo/0023-merge-k-sorted-lists/0023-merge-k-sorted-lists.ts
+ N은 node의 총 개수
+ 모든 value 들을 array에 담는 데 O(N) 
+ value들을 정렬할 때, O(N log(N))
+ linked list를 다시 만들 때, O(N)의 시간
+ value들을 정렬하기 위해서 만든 array가 O(N) 
+ linked list를 만드는 데 사용되는 공간이 O(N)
=> 23. Merge k Sorted Lists / Hard / Typescript

yeongrok/0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.js, yeongrok/0026-remove-duplicates-from-sorted-array/README.md
- 인자로 사용한 원본 배열에서 중복 값을 제거하고 모든 값을 앞으로 몬 다음 나머지엔 `"_"`를 채워야 한다.
- 원본 배열을 `Set()`으로 한번 감쌌다가 spread 연산자로 풀어서 임시로 `nonDuplicated`라는 배열을 만든다.
- 원본 배열이 수정되어야 하므로 `splice` 메서드를 사용해 `nonDuplicated`의 값을 원본 배열의 맨 앞에서부터 채운다.
그 다음 다시 `splice`로 나머지는 `"_"`로 채운다.
- `nonDuplicated`의 길이가 `k`이므로 이를 반환한다.
- `new Set(array)`: O(n)
- `[...array]`: O(n)
- `Array.splice()`: O(n)
- 배열 `nonDuplicated`을 생성하는데 그 길이가 k.
- 그 외엔 원본 배열 수정하므로 추가적으로 사용하는 공간이 더 있지는 않음
=> 26. Remove Duplicates from Sorted Array / Easy / JavaScript

yeongrok/0022-generate-parentheses/0022-generate-parentheses.js, yeongrok/0022-generate-parentheses/README.md
후아 일단 풀었다는데에 감격 T_T 성능 구려도 괜찮아 내 코드
1. 이진 트리를 생성함
2. 루트 노드의 value는 `(`임. 시작부터 닫아버리면 invalid parentheses 니까
3. 각 노드의 left엔 `(`, right엔 `)`을 value로 갖는 노드가 올 수 있는데,
left, right node를 추가 가능할지 판단할 땐 아래 조건 확인.
- isOpenable: 아직 사용 안 한 괄호들 중에서 `)`가 남아 있고, `)`의 수가 `(`와 같거나 보다 많은가?
- isClosable: 이미 사용한 괄호들 중에서 `(`의 수가 `)`보다 많은가?
4. 그리고 left, right 노드에 대해서도 각각 그 하위 노드를 추가하는 함수를 호출해줌. (재귀)
5. 재귀 종료 조건은 인자로 들어온 노드가 leaf일 때이므로,
leaf 부터 root까지의 value를 역으로 쌓아서 괄호 조합 문자열을 `results`배열에 저장해둠
=> leaf에 도달할 때마다 `results` 배열에 항목이 추가되고, 함수가 종료되면 `results` 완성
6. 최종적으로 `results` 반환!
=> 22. Generate Parentheses / Medium / JavaScript

eunjoo/0022-generate-parentheses/0022-generate-parentheses.ts, eunjoo/0022-generate-parentheses/README.md
> 0 0 
> 1 0 (
> 2 0 ((
> 3 0 (((
> 3 1 ((()
> 3 2 ((())
**3 3 ((()))** < -- return
> 2 1 (()
> 3 1 (()(
> 3 2 (()()
**3 3 (()())** < -- return
> 2 2 (())
> 3 2 (())(
**3 3 (())()** < -- return
> 1 1 ()
> 2 1 ()(
> 3 1 ()((
> 3 2 ()(()
**3 3 ()(())** < -- return
> 2 2 ()()
> 3 2 ()()(
**3 3 ()()()** < -- return
+ 라고 하는데 이해가 도통 안됩니다.... 눈물....
+ 깊이 우선 탐색 (DFS - depth first search)
+ 깊은 부분을 우선적으로 탐색하는 알고리즘
+ stack 또는 queue 사용 가능
+ 인접 행렬에서의 시간 복잡도 (N = 정점의 수, E = 간선(노드)의 수)
+ DFS(x)가 N번 호출 -> 전체 DFS 알고리즘의 시간 복잡도 : O(N * N) => O(N ^ 2)
+ 인접리스트에서의 시간 복잡도 (N = 정점의 수, E = 간선(노드)의 수)
+ 인접행렬과 마찬가지로 DFS(x)는 N번 호출
+ DFS(X)의 시간 복잡도 : O(N+E)
=> 22. Generate Parentheses / Medium / Typescript

eunjoo/0028-find-the-index-of-the-first-occurrence-in-a-string/0028-find-the-index-of-the-first-occurrence-in-a-string.ts, eunjoo/0028-find-the-index-of-the-first-occurrence-in-a-string/README.md
=> 28. Find the Index of the First Occurrence in a String / Easy / TypeScript

eunjoo/0029-divide-two-integers/0029-divide-two-integers.ts
+ 경계 조건이 되는 경우들을 모두 고려해주고, 이외의 경우는 Math.truc를 사용해서 문제의 해답을 찾는다.
+ Math.trunc 는 Math.floor와 Math.ceil 로도 풀 수 있다.
https://www.scaler.com/topics/javascript-math-pow/
=> 29. Divide Two Integers / Medium / TypeScript
